### ISSUE TITLE
有关106点3D人脸模型的点

### ISSUE THREAD

**Issue by leizhu1989** [JACKYLUO1991/FaceLandmarks#2]
作者您好！请问106个点3d模型对应的点有吗

**Comment by JACKYLUO1991** [comment]
这个没有 你可以关注一下mediapipe的脸部landmark





------------------ 原始邮件 ------------------
发件人: leizhu1989 ***@***.***&gt;
发送时间: 2022年3月14日 16:59
收件人: JACKYLUO1991/FaceLandmarks ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [JACKYLUO1991/FaceLandmarks] 有关106点3D人脸模型的点 (Issue #2)





 
作者您好！请问106个点3d模型对应的点有吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
